### ISSUE TITLE
Set on non-existant path results in error

### ISSUE THREAD

**Issue by lewisl9029** [Yomguithereal/baobab#253]
I recently took some time to upgrade a project using baobab 0.4.x to 1.x and found this regression:

Doing something like this: 
```js
let baobab = new Baobab({});
let cursor = baobab.select(['nonexistent']);
cursor.set(['key'], 'test');
```

Will result in the following error:

```
Error: baobab.Cursor.set: could not solve dynamic path.
    at Error (native)
    at Cursor.pathPolymorphism (http://localhost:8100/libraries.js:62236:45)
    at Cursor.System.register.Cursor.(anonymous function) [as set] (http://localhost:8100/libraries.js:62244:61)
    at eval (http://localhost:8100/services/state/state-service.js!eval:91:16)
    at processQueue (http://localhost:8100/libraries.js:5941:33)
    at http://localhost:8100/libraries.js:5958:13
```

In 0.4.x, it would correctly populate the path of the cursor and then set the values on it. 

The old behavior seems to be more ideal to me. Was this change deliberate or just a bug?

**Comment by Yomguithereal** [comment]
Hello @lewisl9029. Seems like a bug. Let me check that.

**Comment by zgababa** [comment]
+1

**Comment by Yomguithereal** [comment]
I must check that but I think that this is corrected in v2. Do you need a legacy update for v1 somehow?
