### ISSUE TITLE
v2: `set` from facet fails

### ISSUE THREAD

**Issue by saulshanabrook** [Yomguithereal/baobab#323]
When I try calling `tree.set({})`, where the tree contains a facet (called `$system`)

```javascript
Uncaught TypeError: Cannot assign to read only property '$system' of #<Object>
    at solveMask (eval at <anonymous> (http://localhost:8080/main.js:1970:2), <anonymous>:312:15)
    at solveMask (eval at <anonymous> (http://localhost:8080/main.js:1970:2), <anonymous>:321:7)
    at solveMask (eval at <anonymous> (http://localhost:8080/main.js:1970:2), <anonymous>:321:7)
    at solveMask (eval at <anonymous> (http://localhost:8080/main.js:1970:2), <anonymous>:321:7)
    at getIn (eval at <anonymous> (http://localhost:8080/main.js:1970:2), <anonymous>:396:23)
    at Baobab.update (eval at <anonymous> (http://localhost:8080/main.js:1946:2), <anonymous>:274:39)
    at Cursor.(anonymous function) [as set] (eval at <anonymous> (http://localhost:8080/main.js:1964:2), <anonymous>:800:22)
    at Baobab._this.(anonymous function) [as set] (eval at <anonymous> (http://localhost:8080/main.js:1946:2), <anonymous>:142:33)
    at Object.eval (eval at evaluate (unknown source), <anonymous>:1:6)
    at Object.InjectedScript._evaluateOn (<anonymous>:875:55)
```

Do you think there is a possibility of using a method like set in a path that does have facets? And just replacing the data?

**Comment by saulshanabrook** [comment]
I see, the problem was I had a computed facet value so I couldn't set.

**Comment by saulshanabrook** [comment]
Do you think there is a possibility of using a method like `set` in a path that does have facets? And just replacing the data?

**Comment by christianalfoni** [comment]
Hi there,

Yes, just pointing out that $system is the state property.

I think it is important to be able to reset the whole tree or parts of the tree where facets gets "special treatment". As mentioned #324

The facet syntax looks really nice btw :-)

**Comment by christianalfoni** [comment]
And hi again!

Just wanted to mention I made a fix to this in Cerebral-Baobab-React. It traverses the tree and skips facets, and set all other values. It is not the most performant way, but it works for now.

Maybe this is an idea for "set" of Baobab? Or event its own "import"?

**Comment by Yomguithereal** [comment]
Normally, Baobab v2 won't allow you to set `read-only` paths. By this I mean a path is  `read-only` if one of the steps, but not the last one, is a facet. Because one should not be able to update a facet's data.

However, you should be able to replace a facet's definition somehow.

```js
// This should throw:
tree.set(['one', '$system', 'two'], whatever);

// This should work
tree.set(['one', '$system'], newFacetDefinition);
```

If this does not work, then we have a problem ^^.

**Comment by christianalfoni** [comment]
Ah, yeah, immutable store works a bit different I see. So the facets are just a definition, does not contain a state VALUE of its own... remember we discussed having an input on a facet. But yeah, okay.

So basically what would be great is an "export" that skips the facets... OR, we just use `get()` and when inserting a new tree paths that points to a facet are just ignored. That way you can safely just use `get()` to keep the state and at a later point just `set()` the tree again, where the facet values are not overwriting facet definitions, but ignored. The facets will just recalculate themselves as the tree is new.

Does that make sense?

**Comment by christianalfoni** [comment]
Lets continue on #324  :-)
