### ISSUE TITLE
npm run lint does not work

### ISSUE THREAD

**Issue by kirjs** [Yomguithereal/baobab#384]
```bash
$ npm run lint

> baobab@2.1.0 lint /Users/kirjs/code/baobab
> eslint ./*.js && eslint ./src

module.js:338
    throw err;
          ^
Error: Cannot find module 'eslint-plugin-no-class'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/kirjs/code/baobab/node_modules/eslint/lib/cli-engine.js:124:26
    at Array.forEach (native)
    at loadPlugins (/Users/kirjs/code/baobab/node_modules/eslint/lib/cli-engine.js:115:21)
    at processText (/Users/kirjs/code/baobab/node_modules/eslint/lib/cli-engine.js:202:5)
    at processFile (/Users/kirjs/code/baobab/node_modules/eslint/lib/cli-engine.js:262:18)
    at executeOnFile (/Users/kirjs/code/baobab/node_modules/eslint/lib/cli-engine.js:609:23)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/iojs" "/usr/local/bin/npm" "run" "lint"
npm ERR! node v2.4.0
npm ERR! npm  v2.13.0
npm ERR! code ELIFECYCLE
npm ERR! baobab@2.1.0 lint: `eslint ./*.js && eslint ./src`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the baobab@2.1.0 lint script 'eslint ./*.js && eslint ./src'.
npm ERR! This is most likely a problem with the baobab package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint ./*.js && eslint ./src
npm ERR! You can get their info via:
npm ERR!     npm owner ls baobab
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kirjs/code/baobab/npm-debug.log
```

Just installing missing libraries causes version conflict.

**Comment by Yomguithereal** [comment]
I cannot reproduce your bug. I am using node v0.12 and I guess this issue is related to the deps when using newer node versions. I should check and fix the linter anyway. Let me install nvm and investigate further.

**Comment by Yomguithereal** [comment]
Is this still the case @kirjs?

**Comment by kirjs** [comment]
Let's keep it closed
